import json
import re
import urllib.error
import urllib.request
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any

from chzzk_downloader.config import DEFAULT_COOKIE_FILE_PATH


class SessionStatus(Enum):
    """쿠키 세션 실시간 인증 상태."""

    VALID = "VALID"
    EXPIRED = "EXPIRED"
    INVALID = "INVALID"
    NETWORK_ERROR = "NETWORK_ERROR"
    NO_COOKIES = "NO_COOKIES"


_custom_cookie_path: Path | None = None
_last_session_status: SessionStatus = SessionStatus.NO_COOKIES
_last_session_message: str = "등록된 쿠키 없음"


def set_custom_cookie_path(path: Path | None) -> None:
    """테스트 또는 사용자 설정용 커스텀 쿠키 파일 경로를 지정합니다."""
    global _custom_cookie_path
    _custom_cookie_path = path


def get_cookie_file_path() -> Path:
    """현재 활성화된 쿠키 파일 경로를 반환합니다."""
    if _custom_cookie_path is not None:
        return _custom_cookie_path
    return DEFAULT_COOKIE_FILE_PATH


def parse_cookie_text(text: str) -> tuple[bool, str, str]:
    """입력된 쿠키 문자열(Netscape 또는 HTTP Header Raw 형식)을 파싱하고 검증합니다.

    Returns:
        (is_valid, converted_netscape_content, message)
    """
    cleaned = text.strip()
    if not cleaned:
        return False, "", "쿠키 내용이 비어 있습니다."

    # 1. Netscape HTTP Cookie File 포맷 검사
    lines = cleaned.splitlines()
    is_netscape = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("# Netscape") or stripped.startswith("# HTTP Cookie"):
            is_netscape = True
            break
        parts = stripped.split("\t")
        if len(parts) >= 7:
            is_netscape = True
            break

    if is_netscape:
        # 필수 쿠키 NID_AUT 또는 NID_SES 존재 확인
        has_aut = any("NID_AUT" in line for line in lines)
        has_ses = any("NID_SES" in line for line in lines)
        if not (has_aut or has_ses):
            return (
                False,
                "",
                "네이버 로그인 필수 쿠키(NID_AUT 또는 NID_SES)를 찾을 수 없습니다.",
            )
        # 헤더가 없으면 보강
        header = "# Netscape HTTP Cookie File\n# Generated by Chzzk Downloader\n"
        if not cleaned.startswith("#"):
            cleaned = header + cleaned
        return True, cleaned, "유효한 Netscape 쿠키 형식이 확인되었습니다."

    # 2. HTTP Raw Header (KEY=VALUE; ...) 형식 파싱
    cookie_dict: dict[str, str] = {}
    matches = re.finditer(r"([a-zA-Z0-9_\-]+)\s*=\s*([^;,\s\r\n]+)", cleaned)
    for match in matches:
        k, v = match.group(1), match.group(2)
        cookie_dict[k] = v

    if not cookie_dict:
        return False, "", "인식 가능한 쿠키 항목이 없습니다."

    has_aut = "NID_AUT" in cookie_dict
    has_ses = "NID_SES" in cookie_dict
    if not (has_aut or has_ses):
        return (
            False,
            "",
            "네이버 로그인 필수 쿠키(NID_AUT 또는 NID_SES)를 찾을 수 없습니다.",
        )

    # Netscape 포맷으로 변환
    netscape_lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Chzzk Downloader from raw cookie string",
    ]
    for k, v in cookie_dict.items():
        # domain, flag, path, secure, expiration, name, value
        netscape_lines.append(f".naver.com\tTRUE\t/\tFALSE\t2147483647\t{k}\t{v}")

    converted_text = "\n".join(netscape_lines) + "\n"
    found_keys = [k for k in ["NID_AUT", "NID_SES"] if k in cookie_dict]
    return (
        True,
        converted_text,
        f"성공: {len(cookie_dict)}개 쿠키를 Netscape 포맷으로 변환했습니다 ({', '.join(found_keys)} 포함).",
    )


def save_cookies_text(text: str, cookie_path: Path | None = None) -> tuple[bool, str]:
    """쿠키 텍스트를 파싱하여 검증 후 파일로 저장합니다."""
    target_path = cookie_path or get_cookie_file_path()
    is_valid, content, msg = parse_cookie_text(text)
    if not is_valid:
        return False, msg

    try:
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")
        keys = []
        if "NID_AUT" in content:
            keys.append("NID_AUT")
        if "NID_SES" in content:
            keys.append("NID_SES")
        key_str = ", ".join(keys) if keys else "유효 쿠키"
        set_last_session_status(SessionStatus.VALID, f"쿠키 등록됨 ({key_str} 확인)")
        return True, msg
    except Exception as e:
        return False, f"쿠키 파일 저장 실패: {e}"


def get_cookies_text(cookie_path: Path | None = None) -> str:
    """현재 저장된 쿠키 파일의 원문 텍스트를 반환합니다."""
    target_path = cookie_path or get_cookie_file_path()
    if target_path.is_file():
        try:
            return target_path.read_text(encoding="utf-8")
        except Exception:
            return ""
    return ""


def load_cookie_file(
    src_path: Path, cookie_path: Path | None = None
) -> tuple[bool, str]:
    """외부 쿠키 파일(*.txt)을 읽어 검증 후 저장합니다."""
    if not src_path.is_file():
        return False, f"파일이 존재하지 않습니다: {src_path}"

    try:
        text = src_path.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        return False, f"파일 읽기 오류: {e}"

    return save_cookies_text(text, cookie_path=cookie_path)


def export_cookie_file(
    target_path: Path, cookie_path: Path | None = None
) -> tuple[bool, str]:
    """현재 저장된 쿠키를 외부 파일로 내보냅니다."""
    src_path = cookie_path or get_cookie_file_path()
    if not src_path.is_file():
        return False, "내보낼 등록된 쿠키가 없습니다."

    try:
        content = src_path.read_text(encoding="utf-8")
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")
        return True, f"쿠키 파일 내보내기 완료: {target_path}"
    except Exception as e:
        return False, f"내보내기 실패: {e}"


def clear_cookies(cookie_path: Path | None = None) -> None:
    """저장된 쿠키 파일을 삭제하여 초기화합니다."""
    global _last_session_status, _last_session_message
    target_path = cookie_path or get_cookie_file_path()
    if target_path.is_file():
        try:
            target_path.unlink()
        except Exception:
            pass
    _last_session_status = SessionStatus.NO_COOKIES
    _last_session_message = "등록된 쿠키 없음"


def has_valid_cookies(cookie_path: Path | None = None) -> bool:
    """현재 유효한 네이버 로그인 쿠키가 저장되어 있는지 확인합니다."""
    target_path = cookie_path or get_cookie_file_path()
    if not target_path.is_file():
        return False
    try:
        content = target_path.read_text(encoding="utf-8")
        return "NID_AUT" in content or "NID_SES" in content
    except Exception:
        return False


def get_last_session_status() -> tuple[SessionStatus, str]:
    """최근 세션 검증 결과 상태와 메시지를 반환합니다."""
    return _last_session_status, _last_session_message


def set_last_session_status(status: SessionStatus, message: str) -> None:
    """세션 검증 상태와 메시지를 갱신합니다."""
    global _last_session_status, _last_session_message
    _last_session_status = status
    _last_session_message = message


def get_cookie_status_summary(cookie_path: Path | None = None) -> str:
    """현재 쿠키 상태에 대한 사용자 친화적인 요약 문구를 반환합니다."""
    target_path = cookie_path or get_cookie_file_path()
    if not target_path.is_file():
        return "등록된 쿠키 없음"

    if _last_session_status == SessionStatus.EXPIRED:
        return "쿠키 만료됨 (재로그인 필요)"

    try:
        content = target_path.read_text(encoding="utf-8")
        has_aut = "NID_AUT" in content
        has_ses = "NID_SES" in content
    except Exception:
        return "쿠키 파일 읽기 오류"

    if not (has_aut or has_ses):
        return "유효하지 않은 쿠키 파일"

    if (
        _last_session_status == SessionStatus.VALID
        and "최근 확인" in _last_session_message
    ):
        return _last_session_message

    if has_aut and has_ses:
        return "쿠키 등록됨 (NID_AUT, NID_SES 확인)"
    if has_aut:
        return "쿠키 등록됨 (NID_AUT 확인)"
    if has_ses:
        return "쿠키 등록됨 (NID_SES 확인)"
    return "유효하지 않은 쿠키 파일"


def _to_str(val: Any) -> str:
    if isinstance(val, str):
        return val
    try:
        return bytes(val).decode("utf-8", errors="ignore")
    except Exception:
        return str(val)


def save_network_cookies(
    cookies: list[Any],
    cookie_path: Path | None = None,
) -> tuple[bool, str]:
    """QNetworkCookie 또는 dict 목록에서 네이버 쿠키를 추출하여 Netscape 파일로 저장합니다."""
    netscape_lines = [
        "# Netscape HTTP Cookie File",
        "# Extracted from Naver Login by Chzzk Downloader",
    ]
    found_auth: list[str] = []
    seen: set[str] = set()

    for c in cookies:
        try:
            if isinstance(c, dict):
                name = _to_str(c.get("name", "")).strip()
                value = _to_str(c.get("value", "")).strip()
                domain = _to_str(c.get("domain", "")).strip()
                path = _to_str(c.get("path", "/")).strip() or "/"
                is_secure = bool(c.get("is_secure", True))
            else:
                raw_name = c.name() if hasattr(c, "name") else getattr(c, "name", "")
                name = _to_str(raw_name).strip()

                raw_val = c.value() if hasattr(c, "value") else getattr(c, "value", "")
                value = _to_str(raw_val).strip()

                domain = _to_str(
                    c.domain() if hasattr(c, "domain") else getattr(c, "domain", "")
                ).strip()
                path = (
                    _to_str(
                        c.path() if hasattr(c, "path") else getattr(c, "path", "/")
                    ).strip()
                    or "/"
                )
                is_secure = (
                    c.isSecure()
                    if hasattr(c, "isSecure")
                    else getattr(c, "is_secure", False)
                )
        except Exception:
            continue

        if "naver.com" not in domain or not name or not value:
            continue

        if not domain.startswith("."):
            domain = f".{domain}"

        if name in seen:
            continue
        seen.add(name)

        if name in ("NID_AUT", "NID_SES") and name not in found_auth:
            found_auth.append(name)

        secure_str = "TRUE" if is_secure else "FALSE"
        # 기본 만료일: 영구 보관용 2038년
        netscape_lines.append(
            f"{domain}\tTRUE\t{path}\t{secure_str}\t2147483647\t{name}\t{value}"
        )

    if not found_auth:
        return (
            False,
            "네이버 로그인 인증 쿠키(NID_AUT 또는 NID_SES)가 감지되지 않았습니다.",
        )

    content = "\n".join(netscape_lines) + "\n"
    target_path = cookie_path or get_cookie_file_path()
    try:
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")
        found_auth_str = ", ".join(found_auth)
        set_last_session_status(
            SessionStatus.VALID, f"쿠키 등록됨 ({found_auth_str} 확인)"
        )
        return (
            True,
            f"네이버 로그인이 완료되어 쿠키가 저장되었습니다 ({', '.join(found_auth)}).",
        )
    except Exception as e:
        return False, f"쿠키 파일 쓰기 오류: {e}"


def get_cookie_dict(cookie_path: Path | None = None) -> dict[str, str]:
    """저장된 쿠키 파일에서 키-값 딕셔너리를 추출합니다."""
    target_path = cookie_path or get_cookie_file_path()
    if not target_path.is_file():
        return {}

    try:
        content = target_path.read_text(encoding="utf-8")
    except Exception:
        return {}

    cookies: dict[str, str] = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            name, value = parts[5].strip(), parts[6].strip()
            if name and value:
                cookies[name] = value

    if not cookies:
        for m in re.finditer(r"([A-Za-z0-9_]+)=([^;]+)", content):
            cookies[m.group(1).strip()] = m.group(2).strip()

    return cookies


def verify_cookie_session(
    cookie_path: Path | None = None,
    timeout: float = 3.0,
) -> tuple[SessionStatus, str]:
    """치지직 API를 호출하여 저장된 네이버 로그인 쿠키의 실제 유효성을 검증합니다.

    Returns:
        (SessionStatus, status_message)
    """
    cookie_dict = get_cookie_dict(cookie_path)
    if not ("NID_AUT" in cookie_dict or "NID_SES" in cookie_dict):
        status = SessionStatus.NO_COOKIES
        msg = "등록된 쿠키 없음"
        set_last_session_status(status, msg)
        return status, msg

    cookie_header = "; ".join(f"{k}={v}" for k, v in cookie_dict.items())
    req = urllib.request.Request(
        "https://api.chzzk.naver.com/service/v1/users/me",
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
            ),
            "Cookie": cookie_header,
        },
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="ignore")
            data = json.loads(body)
            code = data.get("code")
            if code == 200:
                content = data.get("content") or {}
                nickname = content.get("nickname", "")
                now_str = datetime.now().strftime("%H:%M")
                msg = (
                    f"쿠키 등록됨 (NID_AUT, NID_SES 확인 · 최근 확인: {now_str})"
                    if not nickname
                    else f"쿠키 등록됨 ({nickname} · 최근 확인: {now_str})"
                )
                set_last_session_status(SessionStatus.VALID, msg)
                return SessionStatus.VALID, msg
            else:
                msg = "쿠키 만료됨 (재로그인 필요)"
                set_last_session_status(SessionStatus.EXPIRED, msg)
                return SessionStatus.EXPIRED, msg
    except urllib.error.HTTPError as e:
        if e.code == 401:
            status = SessionStatus.EXPIRED
            msg = "쿠키 만료됨 (재로그인 필요)"
        elif e.code in (400, 403):
            status = SessionStatus.INVALID
            msg = f"유효하지 않은 쿠키 (HTTP {e.code})"
        else:
            status = SessionStatus.NETWORK_ERROR
            msg = f"서버 오류 (HTTP {e.code})"
        set_last_session_status(status, msg)
        return status, msg
    except (urllib.error.URLError, TimeoutError, OSError):
        status = SessionStatus.NETWORK_ERROR
        msg = "네트워크 연결 실패 (확인 불가)"
        set_last_session_status(status, msg)
        return status, msg
    except Exception as e:
        status = SessionStatus.NETWORK_ERROR
        msg = f"인증 확인 실패: {e}"
        set_last_session_status(status, msg)
        return status, msg
